# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'potc_gui_v_4.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(950, 700))
        MainWindow.setMaximumSize(QtCore.QSize(950, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_selection_analysis = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_selection_analysis.setGeometry(QtCore.QRect(20, 20, 570, 330))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_selection_analysis.setFont(font)
        self.groupBox_selection_analysis.setObjectName("groupBox_selection_analysis")
        self.comboBox_select_threshold_type = QtWidgets.QComboBox(self.groupBox_selection_analysis)
        self.comboBox_select_threshold_type.setGeometry(QtCore.QRect(275, 150, 150, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_select_threshold_type.setFont(font)
        self.comboBox_select_threshold_type.setObjectName("comboBox_select_threshold_type")
        self.label_5 = QtWidgets.QLabel(self.groupBox_selection_analysis)
        self.label_5.setGeometry(QtCore.QRect(0, 150, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_threshold_value = QtWidgets.QDoubleSpinBox(self.groupBox_selection_analysis)
        self.doubleSpinBox_threshold_value.setGeometry(QtCore.QRect(275, 200, 100, 35))
        self.doubleSpinBox_threshold_value.setDecimals(5)
        self.doubleSpinBox_threshold_value.setMaximum(1.0)
        self.doubleSpinBox_threshold_value.setSingleStep(0.05)
        self.doubleSpinBox_threshold_value.setProperty("value", 0.5)
        self.doubleSpinBox_threshold_value.setObjectName("doubleSpinBox_threshold_value")
        self.label_8 = QtWidgets.QLabel(self.groupBox_selection_analysis)
        self.label_8.setGeometry(QtCore.QRect(0, 200, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_selection_analysis)
        self.label_9.setGeometry(QtCore.QRect(0, 250, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.spinBox_route_count = QtWidgets.QSpinBox(self.groupBox_selection_analysis)
        self.spinBox_route_count.setGeometry(QtCore.QRect(275, 250, 100, 35))
        self.spinBox_route_count.setMaximum(100000)
        self.spinBox_route_count.setObjectName("spinBox_route_count")
        self.label_10 = QtWidgets.QLabel(self.groupBox_selection_analysis)
        self.label_10.setGeometry(QtCore.QRect(120, 290, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.groupBox_selection_analysis)
        self.label_3.setGeometry(QtCore.QRect(0, 100, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox_load_data = QtWidgets.QComboBox(self.groupBox_selection_analysis)
        self.comboBox_load_data.setGeometry(QtCore.QRect(275, 100, 150, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_load_data.setFont(font)
        self.comboBox_load_data.setObjectName("comboBox_load_data")
        self.spinBox_robot_route_count = QtWidgets.QSpinBox(self.groupBox_selection_analysis)
        self.spinBox_robot_route_count.setGeometry(QtCore.QRect(275, 50, 100, 35))
        self.spinBox_robot_route_count.setMinimum(1)
        self.spinBox_robot_route_count.setMaximum(1000)
        self.spinBox_robot_route_count.setObjectName("spinBox_robot_route_count")
        self.pushButton_set_robot_count = QtWidgets.QPushButton(self.groupBox_selection_analysis)
        self.pushButton_set_robot_count.setGeometry(QtCore.QRect(460, 40, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_set_robot_count.setFont(font)
        self.pushButton_set_robot_count.setObjectName("pushButton_set_robot_count")
        self.label_11 = QtWidgets.QLabel(self.groupBox_selection_analysis)
        self.label_11.setGeometry(QtCore.QRect(0, 50, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.checkBox_load_data = QtWidgets.QCheckBox(self.groupBox_selection_analysis)
        self.checkBox_load_data.setGeometry(QtCore.QRect(450, 100, 120, 35))
        self.checkBox_load_data.setObjectName("checkBox_load_data")
        self.checkBox_select_threshold_type = QtWidgets.QCheckBox(self.groupBox_selection_analysis)
        self.checkBox_select_threshold_type.setGeometry(QtCore.QRect(450, 150, 120, 35))
        self.checkBox_select_threshold_type.setObjectName("checkBox_select_threshold_type")
        self.plainTextEdit_result_view = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_result_view.setGeometry(QtCore.QRect(620, 35, 300, 500))
        self.plainTextEdit_result_view.setReadOnly(True)
        self.plainTextEdit_result_view.setPlainText("")
        self.plainTextEdit_result_view.setObjectName("plainTextEdit_result_view")
        self.pushButton_start_analysis = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_analysis.setGeometry(QtCore.QRect(690, 550, 150, 75))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_start_analysis.setFont(font)
        self.pushButton_start_analysis.setObjectName("pushButton_start_analysis")
        self.groupBox_robot_configuration = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_robot_configuration.setEnabled(False)
        self.groupBox_robot_configuration.setGeometry(QtCore.QRect(20, 400, 570, 271))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_robot_configuration.setFont(font)
        self.groupBox_robot_configuration.setObjectName("groupBox_robot_configuration")
        self.label_12 = QtWidgets.QLabel(self.groupBox_robot_configuration)
        self.label_12.setGeometry(QtCore.QRect(0, 30, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.comboBox_select_robot = QtWidgets.QComboBox(self.groupBox_robot_configuration)
        self.comboBox_select_robot.setGeometry(QtCore.QRect(275, 30, 150, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_select_robot.setFont(font)
        self.comboBox_select_robot.setObjectName("comboBox_select_robot")
        self.label_7 = QtWidgets.QLabel(self.groupBox_robot_configuration)
        self.label_7.setGeometry(QtCore.QRect(400, 230, 71, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_robot_configuration)
        self.label_6.setGeometry(QtCore.QRect(400, 180, 71, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.doubleSpinBox_nominal_capacity_value = QtWidgets.QDoubleSpinBox(self.groupBox_robot_configuration)
        self.doubleSpinBox_nominal_capacity_value.setGeometry(QtCore.QRect(275, 230, 100, 35))
        self.doubleSpinBox_nominal_capacity_value.setDecimals(1)
        self.doubleSpinBox_nominal_capacity_value.setMaximum(100000.0)
        self.doubleSpinBox_nominal_capacity_value.setSingleStep(0.5)
        self.doubleSpinBox_nominal_capacity_value.setObjectName("doubleSpinBox_nominal_capacity_value")
        self.doubleSpinBox_robot_speed_value = QtWidgets.QDoubleSpinBox(self.groupBox_robot_configuration)
        self.doubleSpinBox_robot_speed_value.setGeometry(QtCore.QRect(275, 180, 100, 35))
        self.doubleSpinBox_robot_speed_value.setDecimals(3)
        self.doubleSpinBox_robot_speed_value.setMaximum(100.0)
        self.doubleSpinBox_robot_speed_value.setObjectName("doubleSpinBox_robot_speed_value")
        self.label_4 = QtWidgets.QLabel(self.groupBox_robot_configuration)
        self.label_4.setGeometry(QtCore.QRect(0, 230, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_hazard_rate_value = QtWidgets.QLineEdit(self.groupBox_robot_configuration)
        self.lineEdit_hazard_rate_value.setGeometry(QtCore.QRect(275, 80, 200, 35))
        self.lineEdit_hazard_rate_value.setObjectName("lineEdit_hazard_rate_value")
        self.label = QtWidgets.QLabel(self.groupBox_robot_configuration)
        self.label.setGeometry(QtCore.QRect(0, 80, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_robot_configuration)
        self.label_2.setGeometry(QtCore.QRect(0, 180, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_start_reliability_value = QtWidgets.QLineEdit(self.groupBox_robot_configuration)
        self.lineEdit_start_reliability_value.setGeometry(QtCore.QRect(275, 130, 200, 35))
        self.lineEdit_start_reliability_value.setObjectName("lineEdit_start_reliability_value")
        self.label_13 = QtWidgets.QLabel(self.groupBox_robot_configuration)
        self.label_13.setGeometry(QtCore.QRect(0, 130, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prognostic Aware Multi Robot Route Planning"))
        self.groupBox_selection_analysis.setTitle(_translate("MainWindow", "Analysis Options"))
        self.label_5.setText(_translate("MainWindow", "Select Threshold Type"))
        self.label_8.setText(_translate("MainWindow", "Threshold Value"))
        self.label_9.setText(_translate("MainWindow", "Route Count"))
        self.label_10.setText(_translate("MainWindow", "Note: It refers to the number of routes to be analyzed. If the value is 0, it refers to the maximum value."))
        self.label_3.setText(_translate("MainWindow", "Use Load Data"))
        self.pushButton_set_robot_count.setText(_translate("MainWindow", "Set Count"))
        self.label_11.setText(_translate("MainWindow", "Set Robot Count"))
        self.checkBox_load_data.setText(_translate("MainWindow", "Both"))
        self.checkBox_select_threshold_type.setText(_translate("MainWindow", "Both"))
        self.pushButton_start_analysis.setText(_translate("MainWindow", "Start Analysis"))
        self.groupBox_robot_configuration.setTitle(_translate("MainWindow", "Robot Configuration"))
        self.label_12.setText(_translate("MainWindow", "Select Robot"))
        self.label_7.setText(_translate("MainWindow", "kg"))
        self.label_6.setText(_translate("MainWindow", "km / h"))
        self.label_4.setText(_translate("MainWindow", "Nominal Capacity Value"))
        self.label.setText(_translate("MainWindow", "Hazard Rate Value"))
        self.label_2.setText(_translate("MainWindow", "Robot Speed Value"))
        self.label_13.setText(_translate("MainWindow", "Start Reliability Value"))

